import streamlit as st
st.write("Bonjour Le monde")
st.title("Mon premier application ")
st.header("Experience sur mon jeu de donnée")
st.subheader(" Mon jeu de donne iris")
st.slider("Longueur du Petal",0.0,5.0)
st.slider("Largeur du Petal",0.0,5.0)
st.slider("Longueur du Metal",0.0,5.0)
st.slider("Largeur du Metal",0.0,5.0)
st.button("Cliquez ici")
st.sidebar.title("Menu latéral")
st.sidebar.write("Bienvenu sur iris")
